# Generated by Django 5.0.4 on 2024-04-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('decibels', models.FloatField()),
                ('frequency', models.FloatField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
